### PR TITLE
fix(miqParser): removes null attributes, fixes pattern, number

### PR DESCRIPTION
**Pull request by rvsia**
- [X] integer => type: number
- [X] removing empty options (fixes checkboxes)
- [X] removing `null` and `''` atributes
- [X] split attributes into true and false category
- [X] `multi` attributes for multi selects
- [X] fixed pattern validators
- [X] removed autofocus
- [x]  Required validator

### CODE REVIEW

**Comment by rvsia** [comment]
@Hyperkid123 Fixed most of the stuff for now. Next step will be to make it future-proof. :smiley_cat: 

However, the integer validator is not still on. :crying_cat_face: Type is number, dataType is integer.

**Comment by Hyperkid123** [comment]
@rvsia i will investigate!

**Comment by Hyperkid123** [comment]
@rvsia i got a fix i've mda a mistake nice catch!

**Pull request merged**
